name: news_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  get: ^4.6.6
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  http: ^1.2.2
  intl: ^0.20.1
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_logo.png
    - assets/images/

flutter icons:
  image_path: "assets/app_logo.png"
  android: true
  ios: true
  app_name: "SwiftBrief"